name: Generate Snake

on:
  # Run automatically every 24h
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo content
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake SVG animation
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Aryanp018
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push the generated files
      - name: Commit and push snake files
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/"
          message: "chore: update snake graph"
          push: true
